name: sc-benchmark
channels:
  - conda-forge
dependencies:
  - python=3.11
  - scanpy
  - anndata
  - pandas
  - numpy=2.2
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - numba
  - leidenalg
  - python-igraph
  - jupyter
  - pip
  - pip:
      - gseapy
      - pytest